Creating tasks

diff --git a/git-auto-merge-decorator.yml b/git-auto-merge-decorator.yml
--- a/git-auto-merge-decorator.yml
+++ b/git-auto-merge-decorator.yml
@@ -1,18 +1,12 @@
 steps:
 - ${{ if and(eq(variables['Decorator.GitAutoMerge.Enabled'], True), eq(variables['System.StageDisplayName'], 'PRD')) }}:
   - task: PowerShell@2
-    displayName: 'Git: Auto Merge (injected from decorator)'
+    displayName: 'Git: Auto Merge - step: clone repository (injected from decorator)'
     inputs:
+      workingDirectory: '$(System.DefaultWorkingDirectory)'
       targetType: 'inline'
       script: |
-        ############      clone repository    ##############
-        echo "##[section]Starting: Clone repository"
-
         echo "before cloning"
-        dir
-
-        cd "$(System.DefaultWorkingDirectory)"
-        echo "after cd System.DefaultWorkingDirectory"
         dir
 
         mkdir _git
@@ -28,10 +22,16 @@ steps:
         cd $(Build.Repository.Name)
         echo "Cloned, Working Dir changed for '$(Build.Repository.Name)'"
 
-        echo "##[section]Finishing: Clone repository"
-
-        ############      auto merge    ##############
-        echo "##[section]Starting: Auto merge"
+  - task: PowerShell@2
+    displayName: 'Git: Auto Merge - step: auto merge (injected from decorator)'
+    inputs:
+      workingDirectory: '$(System.DefaultWorkingDirectory)'
+      targetType: 'inline'
+      script: |
+        dir
+        
+        cd _git
+        cd $(Build.Repository.Name)
 
         git checkout master
         echo "merging on master branch with commit $(Build.SourceVersion)"
@@ -41,30 +41,7 @@ steps:
         if(-not $?){
           echo "##[error] Merge incomplete, aborting"
           echo "##vso[task.logissue type=error] Fail to merge from $(Build.SourceBranchName) to master"
-
-          echo "##[section]Starting: Clean folder"
-
-          echo "before cleaning"
-          dir "$(System.DefaultWorkingDirectory)"
-
-          cd "$(System.DefaultWorkingDirectory)"
-          
-          if ('$(Agent.OS)' -eq 'Linux')
-          {
-            echo "Agent Linux"
-            rm -rf _git
-          }
-          else
-          {
-            echo "Agent Windows"
-            rm -r -force _git
-          }
-
-          echo "after cleaning"
-          dir "$(System.DefaultWorkingDirectory)"
-
-          echo "##[section]Finishing: Clean folder"
-
+          echo "##vso[task.logissue type=error] Your branch is outdated in relation to the master branch, that is, you are trying to remove some commits already published in production. Update your branch with master."
           exit 1
         }
 
@@ -75,16 +52,22 @@ steps:
         if($?){
           echo "master updated with success"
         }
+        else
+        {
+          echo "##vso[task.logissue type=error] Fail to push master branch after merge from $(Build.SourceBranchName)"
+          echo "##vso[task.logissue type=error] There is a problem in your branch, which does not allow the completion of git push."
+          exit 1
+        }
 
-        echo "##[section]Finishing: Auto merge"
-
-        ############      Clean _git folder    ##############
-        echo "##[section]Starting: Clean folder"
-
+  - task: PowerShell@2
+    displayName: 'Git: Auto Merge - step: clean folder (injected from decorator)'
+    condition: succeededOrFailed()
+    inputs:
+      workingDirectory: '$(System.DefaultWorkingDirectory)'
+      targetType: 'inline'
+      script: |
         echo "before cleaning"
-        dir "$(System.DefaultWorkingDirectory)"
-
-        cd "$(System.DefaultWorkingDirectory)"
+        dir
 
         if ('$(Agent.OS)' -eq 'Linux')
         {
@@ -98,6 +81,4 @@ steps:
         }
 
         echo "after cleaning"
-        dir "$(System.DefaultWorkingDirectory)"
-
-        echo "##[section]Finishing: Clean folder"
+        dir
